...

diff --git a/mod/claude/lib/usage/daily b/mod/claude/lib/usage/daily
--- a/mod/claude/lib/usage/daily
+++ b/mod/claude/lib/usage/daily
@@ -14,6 +14,10 @@ ___x_cmd_claude_usage_daily(){
         esac
     done
 
+    [ -d "$___X_CMD_CLAUDE_CODE_DATA_PATH" ] ||{
+        claude:error "$___X_CMD_CLAUDE_CODE_DATA_PATH directory not found. Cannot retrieve Claude Code usage logs."
+        return 1
+    }
 
     [ -n "$date_start" ]    || {
         local x_=; ___x_cmd_claude_usage_util_offset_date_ "$date" -7
@@ -39,7 +43,7 @@ ___x_cmd_claude_usage_date_token_(){
     ___x_cmd_claude_usage_util_offset_date_ "$date" 1
     next_date="$x_"
 
-    ___x_cmd_cmds find "$HOME/.claude/projects" -maxdepth 2 -type f -newermt "$date" ! -newermt "$next_date" -exec cat {} + \
+    ___x_cmd_cmds find "$___X_CMD_CLAUDE_CODE_DATA_PATH" -maxdepth 2 -type f -newermt "$date" ! -newermt "$next_date" -exec cat {} + \
         | ___x_cmd jq --arg day "$date" '
             select(
                 .message.usage?
@@ -135,7 +139,7 @@ ___x_cmd_claude_usage_daily_(){
     local date="$date_start"
 
     while true; do
-        ___x_cmd_claude_usage_date_ "$date"
+        ___x_cmd_claude_usage_date_ "$date" || return $?
         [ "$date" != "$date_end" ] || break
         ___x_cmd_claude_usage_util_offset_date_ "$date" 1; date="$x_"
     done
diff --git a/mod/claude/lib/usage/projects b/mod/claude/lib/usage/projects
--- a/mod/claude/lib/usage/projects
+++ b/mod/claude/lib/usage/projects
@@ -1,12 +1,18 @@
 
 ___x_cmd_claude_usage_projects(){
-    local source="${1:-"$HOME/.claude/projects"}"
+    local source="${1:-"$___X_CMD_CLAUDE_CODE_DATA_PATH"}"
     while [ $# -gt 0 ]; do
         case "$1" in
             -h|--help)          ___x_cmd help -m claude usage projects ; return 0 ;;
             *)                  break ;;
         esac
     done
+
+    [ -d "$source" ] ||{
+        claude:error "$source directory not found. Cannot retrieve Claude Code usage logs."
+        return 1
+    }
+
     {
         printf "%s,%s,%s,%s,%s,%s,%s,%s\n" \
             "project" "models" "cost" "input_tokens" \
@@ -20,6 +26,7 @@ ___x_cmd_claude_usage_projects(){
 
 ___x_cmd_claude_usage_project_token_(){
     local project="$1"
+    [ -d "$project" ] || N=claude M="$project directory not found. Cannot retrieve Claude Code usage logs." log:ret:1
     ___x_cmd_cmds find "$project" -maxdepth 2 -type f -exec cat {} + \
         | ___x_cmd jq '
             select(
@@ -113,6 +120,6 @@ ___x_cmd_claude_usage_projects_(){
     local source="${1}"
     local project=
     ___x_cmd fsiter "$source" | while read -r project; do
-        ___x_cmd_claude_usage_project_ "$source/$project"
+        ___x_cmd_claude_usage_project_ "$source/$project" || return $?
     done
 }
