...

diff --git a/mod/feishu/lib/listen b/mod/feishu/lib/listen
--- a/mod/feishu/lib/listen
+++ b/mod/feishu/lib/listen
@@ -19,38 +19,35 @@ ___x_cmd_feishu_listen(){
     local cur_token
     ____x_cmd_tenant_token ; cur_token="$x_"
 
+        # TODO:
+    local chats=
+    chats="$(___x_cmd_chat_id 20)"
+
     local chatid
     while true; do
         local date=;
         local resp=;
         ___x_cmd date timestamp_ ; date="$x_"
 
-        # TODO:
-        local chats=
-        chats="$(___x_cmd_chat_id 20)"
+
         while [ -z "$resp" ]; do
-            for chatid in $chats; do
-                resp="$(___x_cmd_feishu_getmessages "$chatid" "$date" | ___x_cmd awk0 -m j/json -m j/jiter '
-{ jiparse_after_tokenize(o, $0); }
-END{
-    kp = SUBSEP "\"1\"" SUBSEP "\"data\"" SUBSEP "\"items\""
-    l = o[ kp L ]
-    for (i=1; i<=l; ++i){
-        kp_i = kp SUBSEP "\""i"\""
-        kp_sender_type = kp_i SUBSEP "\"sender\"" SUBSEP "\"sender_type\""
-        if (o[ kp_sender_type ] == "\"user\""){
-            print jstr0(o, kp_i, " ")
-        }
-    }
-}')"
-            done
+            while IFS= read -r chatid; do
+                resp="$(___x_cmd_feishu_getmessages "$chatid" "$date" | ___x_cmd_feishu_parsemsg)" || {
+                    feishu:error "Failed to get updates: $resp"
+                    ___x_cmd sleep 1s
+                    return 1
+                }
+            done <<A
+$chats
+A
         done
 
         if [ -n "$fp" ]; then
             case "$resp" in
                 *"chat"*)
-                        chatid="${resp#*'"chat_id" : "'}"
-                        chatid="${chatid%%'" ,'*}"
+                        # Extract chat_id using pure shell string manipulation
+                        chatid="${resp##*\"chat_id\" : \"}"
+                        chatid="${chatid%%\"*}"
                         ___X_CMD_FEISHU_BOT_DATA="${___X_CMD_FEISHU_BOT_PATH}/data_${chatid}.tsv"
                         ___x_cmd ensurefp "$___X_CMD_FEISHU_BOT_DATA"
                         printf "%s\n" "$resp"  >> "$___X_CMD_FEISHU_BOT_DATA"
@@ -70,4 +67,20 @@ ___x_cmd_feishu_getmessages(){
     local start_time="$2"
     ___x_cmd curl -s "https://open.feishu.cn/open-apis/im/v1/messages?container_id=$chatid&container_id_type=chat&page_size=20&sort_type=ByCreateTimeDesc&start_time=$start_time" \
                   -H "Authorization: Bearer $cur_token"
+}
+
+___x_cmd_feishu_parsemsg(){
+    ___x_cmd awk0 -m j/json -m j/jiter '
+{ jiparse_after_tokenize(o, $0); }
+END{
+    kp = SUBSEP "\"1\"" SUBSEP "\"data\"" SUBSEP "\"items\""
+    l = o[ kp L ]
+    for (i=1; i<=l; ++i){
+        kp_i = kp SUBSEP "\""i"\""
+        kp_sender_type = kp_i SUBSEP "\"sender\"" SUBSEP "\"sender_type\""
+        if (o[ kp_sender_type ] == "\"user\""){
+            print jstr0(o, kp_i, " ")
+        }
+    }
+}'
 }
diff --git a/mod/telegram/lib/listen b/mod/telegram/lib/listen
--- a/mod/telegram/lib/listen
+++ b/mod/telegram/lib/listen
@@ -10,11 +10,11 @@ ___x_cmd_telegram_listen(){
 
     while [ $# -gt 0 ]; do
         case "$1" in
-            -h|--help)      ___x_cmd help -m weixin listen "$@" ; return 0 ;;
-            --json)         format="json" ; shift ;;
-            --timeout)      timeout="$2" ; arg:2:shift ;;
-            --offset)       offset="$2" ; arg:2:shift ;;
-            --fp)           fp=1 ; shift ;;
+            -h|--help)      ___x_cmd help -m telegram listen "$@" ; return 0 ;;
+            --fp)           fp=1 ;          shift ;;
+            --json)         format="json";  shift ;;
+            --timeout)      timeout="$2" ;  arg:2:shift ;;
+            --offset)       offset="$2"  ;  arg:2:shift ;;
             *)              break ;;
         esac
     done
@@ -34,13 +34,17 @@ ___x_cmd_telegram_listen(){
     while true; do
         local chatid
         local resp
-        resp="$(___x_cmd_telegram_getupdates | ___x_cmd jq -c )"
+        resp="$(___x_cmd_telegram_getupdates | ___x_cmd jq -c )" || {
+            telegram:error "Failed to get updates: $resp"
+            ___x_cmd sleep 1s
+            return 1
+        }
 
         local msg
         ___x_cmd jo env . msg=.result <<A
 $resp
 A
-        # [ "$msg" != "[]" ] || continue
+        [ "$msg" != "[]" ] || continue
 
         offset="$(printf "%s\n" "$resp" | ___x_cmd jq ".result[-1].update_id + 1")"
         printf "%s\n" "$offset" > "$offsetfp"
